#ifndef _APPLICATION
#define _APPLICATION

// Do not edit! This file has been automatically generated by CMake
// Framework/Application.h.cmake

#include <Framework/CApplication.h>
#include <Framework/Application_Registration.h>


/// TODO: remove/// TODO: remove/// TODO: remove
#warning 20130108 using namespace dev in CApplication.h will be removed
using namespace dev; /// TODO: remove

#warning 20130108 using namespace usr in CModule.h will be removed
using namespace usr;
/// TODO: remove/// TODO: remove/// TODO: remove


#define DECL_METHODS\
  void FillPathManager()\
  {\
    SetPath("SRC_DIR", "/home/alox/Tesi/workspace/Dummy");\
    SetPath(CONF_DIR,  "/home/alox/Tesi/workspace/Dummy/INI");\
    SetPath(HWS_DIR,   "/home/alox/Tesi/workspace/Dummy/HWS");\
    SetPath(DATA_DIR,  "/home/alox/Tesi/workspace/Dummy/Data");\
  }
  
  
// TODO: Add here other common files for applications

#endif // _APPLICATION
